<a href="https://colab.research.google.com/github/codeep3/DA-data-analysis/blob/COLAB_PRACTICE-_FILES/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [9]:
%%sql

SELECT
  p.categoryname,
  AVG(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS avg_net_revenue_2022,
  AVG(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS avg_net_revenue_2023
FROM
   sales AS s
LEFT JOIN product AS p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  avg_net_revenue_2022  avg_net_revenue_2023
0                          Audio                392.30                425.38
1        Cameras and camcorders                1210.02               1210.96
2                    Cell phones                722.20                623.28
3                      Computers               1565.62               1292.39
4                 Games and Toys                 81.29                 80.83
5                Home Appliances               1755.36               1886.55
6  Music, Movies and Audio Books                386.61                334.58
7                   TV and Video               1535.61               1687.90

In [12]:
%%sql
SELECT
  p.categoryname,
  PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY ( CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate)END)) AS median_sales_2022,
  PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY ( CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate)END)) AS median_sales_2023
FROM
   sales AS s
LEFT JOIN product AS p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  median_sales_2022  median_sales_2023
0                          Audio             257.21             266.59
1        Cameras and camcorders              651.46             672.60
2                    Cell phones             418.60             375.88
3                      Computers             809.70             657.18
4                 Games and Toys              33.78              32.62
5                Home Appliances             791.00             825.25
6  Music, Movies and Audio Books             186.58             159.63
7                   TV and Video             730.46             790.79

In [21]:
%%sql
SELECT
  s.orderdate,
  s.quantity,
  s.netprice,
  CASE
    WHEN s.quantity>= 2  AND s.netprice<  100 THEN ' Multiple Standard Items'
    WHEN s.quantity>= 2  AND s.netprice>= 100 THEN 'Multiple High Value Items'
    WHEN s.quantity<  2  AND s.netprice>= 100 THEN 'Single High Value Item'
    ELSE 'Single Standard Item' END  AS Order_Type
FROM
  sales AS s
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                 order_type
0  2015-01-01         1     98.97       Single Standard Item
1  2015-01-01         1    659.78     Single High Value Item
2  2015-01-01         2     54.38    Multiple Standard Items
3  2015-01-01         4    286.69  Multiple High Value Items
4  2015-01-01         7    135.75  Multiple High Value Items
5  2015-01-01         3    434.30  Multiple High Value Items
6  2015-01-01         1     58.73       Single Standard Item
7  2015-01-01         3     74.99    Multiple Standard Items
8  2015-01-01         2    113.57  Multiple High Value Items
9  2015-01-01         1    499.45     Single High Value Item

In [ ]:
%%SQL